namespace oBiletCase.Infrastructure.Localization;

/// <summary>
/// Migration'larla veritabanına yazılan başlangıç çevirileri. Buradaki bir kaydı değiştirmek/eklemek yeni bir
/// migration gerektirir (<c>dotnet ef migrations add ...</c>); aksi hâlde model snapshot'ı ile çelişir.
/// </summary>
internal static class LocalizationSeedData
{
    private const string Tr = LocalizationCultures.Turkish;
    private const string En = LocalizationCultures.English;

    /// <summary>Eski <c>SharedResource.resx</c> (tr) ve <c>SharedResource.en.resx</c> (en) dosyalarının birebir içeriği.</summary>
    public static IReadOnlyList<LocalizationResource> Resources { get; } =
    [
        new("AppName", Tr, "oBiletCase"),
        new("NavHome", Tr, "Ana Sayfa"),
        new("SkipToContent", Tr, "İçeriğe geç"),
        new("SearchEyebrow", Tr, "Otobüs biletleri"),
        new("SearchTitle", Tr, "Otobüs bileti ara"),
        new("SearchAccent", Tr, "kalkıştan varışa."),
        new("SearchLede", Tr, "Kalkış, varış ve tarihi seçin. Sonuçlar bir sonraki adımda listelenir."),
        new("FooterTagline", Tr, "Basit arama, net sonuç."),
        new("OriginLabel", Tr, "Nereden"),
        new("DestinationLabel", Tr, "Nereye"),
        new("DepartureDateLabel", Tr, "Gidiş Tarihi"),
        new("SwapLocationsLabel", Tr, "Kalkış ve varışı değiştir"),
        new("TodayLabel", Tr, "Bugün"),
        new("TomorrowLabel", Tr, "Yarın"),
        new("SearchButton", Tr, "Sefer Ara"),
        new("OriginPlaceholder", Tr, "Kalkış noktası seçin"),
        new("DestinationPlaceholder", Tr, "Varış noktası seçin"),
        new("ValidationOriginRequired", Tr, "Kalkış noktası seçilmelidir."),
        new("ValidationDestinationRequired", Tr, "Varış noktası seçilmelidir."),
        new("ValidationSameLocation", Tr, "Kalkış ve varış noktası aynı olamaz."),
        new("ValidationPastDate", Tr, "Gidiş tarihi bugünden önce olamaz."),
        new("ValidationDateRequired", Tr, "Gidiş tarihi seçilmelidir."),
        new("ToastDismissLabel", Tr, "Bildirimi kapat"),
        new("LanguageSwitchLabel", Tr, "Dil"),
        new("NoLocationResults", Tr, "Sonuç bulunamadı"),
        new("SearchLocationLoading", Tr, "Aranıyor..."),
        new("SearchLocationError", Tr, "Lokasyonlar yüklenemedi"),
        new("ClearLocationLabel", Tr, "Seçimi temizle"),
        new("DatePickerLabel", Tr, "Gidiş tarihi seçin"),
        new("DatePickerPreviousMonth", Tr, "Önceki ay"),
        new("DatePickerNextMonth", Tr, "Sonraki ay"),
        new("ErrorKicker", Tr, "Bir sorun oluştu"),
        new("ErrorTitle", Tr, "İstek işlenemedi"),
        new("ErrorBody", Tr, "Beklenmeyen bir hata oluştu. Ana sayfadan yeniden deneyebilirsiniz."),
        new("RequestIdLabel", Tr, "İstek numarası"),
        new("BackToSearch", Tr, "Aramaya dön"),
        new("RecentSearchesTitle", Tr, "Son aramalarınız"),
        new("RemoveRecentSearchLabel", Tr, "Bu aramayı kaldır"),
        new("OriginSummaryLabel", Tr, "Kalkış"),
        new("DestinationSummaryLabel", Tr, "Varış"),
        new("DepartureDateSummaryLabel", Tr, "Tarih"),
        new("InvalidSearchNotice", Tr, "Aramanız artık geçerli değil. Lütfen kriterleri kontrol edip tekrar deneyin."),
        new("JourneysResultsTitle", Tr, "Sefer sonuçları"),
        new("JourneysCountSuffix", Tr, "sefer bulundu"),
        new("NoJourneysFoundTitle", Tr, "Bu tarihte sefer bulunamadı"),
        new("NoJourneysFoundBody", Tr, "Farklı bir tarih veya güzergah deneyebilirsiniz."),
        new("JourneysLoadErrorTitle", Tr, "Seferler yüklenemedi"),
        new("JourneysLoadErrorBody", Tr, "Obilet servisine şu anda ulaşılamıyor. Lütfen daha sonra tekrar deneyin."),
        new("DurationLabel", Tr, "Süre"),
        new("AvailableSeatsSuffix", Tr, "boş koltuk"),
        new("ViewOnObiletButton", Tr, "Obilet'te incele"),
        new("PreviousDayLabel", Tr, "Önceki gün"),
        new("NextDayLabel", Tr, "Sonraki gün"),
        new("DayStripLabel", Tr, "Gidiş tarihi"),
        new("SortLabel", Tr, "Sırala"),
        new("SortDepartureAscending", Tr, "Kalkış (erken → geç)"),
        new("SortDepartureDescending", Tr, "Kalkış (geç → erken)"),
        new("SortPriceAscending", Tr, "Fiyat (düşük → yüksek)"),
        new("SortPriceDescending", Tr, "Fiyat (yüksek → düşük)"),
        new("DetailsLabel", Tr, "Detaylar"),
        new("CancellationPolicyLabel", Tr, "İptal koşulu"),
        new("CancellationPolicyValue", Tr, "Kalkıştan en az {0} saat önce iptal edilebilir."),
        new("GovIdRequiredLabel", Tr, "Kimlik zorunluluğu"),
        new("GovIdRequiredYes", Tr, "TC kimlik numarası gerekli"),
        new("GovIdRequiredNo", Tr, "Kimlik numarası gerekmez"),
        new("SeatingPolicyLabel", Tr, "Oturma düzeni"),
        new("SeatingPolicyMixed", Tr, "Kadın-erkek karışık oturulabilir"),
        new("SeatingPolicySeparate", Tr, "Kadın-erkek ayrı oturma düzeni"),
        new("PartnerRatingLabel", Tr, "Firma puanı"),
        new("OvernightBridgeLabel", Tr, "{0}'ı {1}'ye bağlayan gece"),
        new("FiltersTitle", Tr, "Filtrele"),
        new("ClearFiltersButton", Tr, "Filtreleri temizle"),
        new("TimeFilterLabel", Tr, "Kalkış saati"),
        new("TimeFilterNight", Tr, "Gece (00:00–06:00)"),
        new("TimeFilterMorning", Tr, "Sabah (06:00–12:00)"),
        new("TimeFilterAfternoon", Tr, "Öğlen (12:00–18:00)"),
        new("TimeFilterEvening", Tr, "Akşam (18:00–24:00)"),
        new("BusTypeFilterLabel", Tr, "Koltuk düzeni"),
        new("FiltersNoMatchBody", Tr, "Seçtiğiniz filtrelere uyan sefer bulunamadı."),
        new("FiltersAllLabel", Tr, "Tümü"),
        new("FiltersActiveLabel", Tr, "{0} seçili"),
        new("CloseFiltersLabel", Tr, "Kapat"),

        new("AppName", En, "oBiletCase"),
        new("NavHome", En, "Home"),
        new("SkipToContent", En, "Skip to content"),
        new("SearchEyebrow", En, "Bus tickets"),
        new("SearchTitle", En, "Search bus tickets"),
        new("SearchAccent", En, "from here to there."),
        new("SearchLede", En, "Choose origin, destination and date. Results are listed in the next step."),
        new("FooterTagline", En, "Simple search, clear results."),
        new("OriginLabel", En, "From"),
        new("DestinationLabel", En, "To"),
        new("DepartureDateLabel", En, "Departure Date"),
        new("SwapLocationsLabel", En, "Swap origin and destination"),
        new("TodayLabel", En, "Today"),
        new("TomorrowLabel", En, "Tomorrow"),
        new("SearchButton", En, "Search Journeys"),
        new("OriginPlaceholder", En, "Select departure location"),
        new("DestinationPlaceholder", En, "Select arrival location"),
        new("ValidationOriginRequired", En, "Departure location is required."),
        new("ValidationDestinationRequired", En, "Arrival location is required."),
        new("ValidationSameLocation", En, "Departure and arrival location cannot be the same."),
        new("ValidationPastDate", En, "Departure date cannot be in the past."),
        new("ValidationDateRequired", En, "Departure date is required."),
        new("ToastDismissLabel", En, "Dismiss notification"),
        new("LanguageSwitchLabel", En, "Language"),
        new("NoLocationResults", En, "No results found"),
        new("SearchLocationLoading", En, "Searching..."),
        new("SearchLocationError", En, "Locations could not be loaded"),
        new("ClearLocationLabel", En, "Clear selection"),
        new("DatePickerLabel", En, "Choose departure date"),
        new("DatePickerPreviousMonth", En, "Previous month"),
        new("DatePickerNextMonth", En, "Next month"),
        new("ErrorKicker", En, "Something went wrong"),
        new("ErrorTitle", En, "The request could not be processed"),
        new("ErrorBody", En, "An unexpected error occurred. You can try again from the home page."),
        new("RequestIdLabel", En, "Request ID"),
        new("BackToSearch", En, "Back to search"),
        new("RecentSearchesTitle", En, "Your recent searches"),
        new("RemoveRecentSearchLabel", En, "Remove this search"),
        new("OriginSummaryLabel", En, "From"),
        new("DestinationSummaryLabel", En, "To"),
        new("DepartureDateSummaryLabel", En, "Date"),
        new("InvalidSearchNotice", En, "Your search is no longer valid. Please check the criteria and try again."),
        new("JourneysResultsTitle", En, "Journey results"),
        new("JourneysCountSuffix", En, "journeys found"),
        new("NoJourneysFoundTitle", En, "No journeys found for this date"),
        new("NoJourneysFoundBody", En, "Try a different date or route."),
        new("JourneysLoadErrorTitle", En, "Journeys could not be loaded"),
        new("JourneysLoadErrorBody", En, "The Obilet service is currently unreachable. Please try again later."),
        new("DurationLabel", En, "Duration"),
        new("AvailableSeatsSuffix", En, "seats available"),
        new("ViewOnObiletButton", En, "View on Obilet"),
        new("PreviousDayLabel", En, "Previous day"),
        new("NextDayLabel", En, "Next day"),
        new("DayStripLabel", En, "Departure date"),
        new("SortLabel", En, "Sort by"),
        new("SortDepartureAscending", En, "Departure (earliest first)"),
        new("SortDepartureDescending", En, "Departure (latest first)"),
        new("SortPriceAscending", En, "Price (low to high)"),
        new("SortPriceDescending", En, "Price (high to low)"),
        new("DetailsLabel", En, "Details"),
        new("CancellationPolicyLabel", En, "Cancellation policy"),
        new("CancellationPolicyValue", En, "Can be cancelled at least {0} hours before departure."),
        new("GovIdRequiredLabel", En, "ID requirement"),
        new("GovIdRequiredYes", En, "National ID number required"),
        new("GovIdRequiredNo", En, "No ID number required"),
        new("SeatingPolicyLabel", En, "Seating policy"),
        new("SeatingPolicyMixed", En, "Mixed-gender seating allowed"),
        new("SeatingPolicySeparate", En, "Separate seating by gender"),
        new("PartnerRatingLabel", En, "Partner rating"),
        new("OvernightBridgeLabel", En, "Night linking {0} to {1}"),
        new("FiltersTitle", En, "Filters"),
        new("ClearFiltersButton", En, "Clear filters"),
        new("TimeFilterLabel", En, "Departure time"),
        new("TimeFilterNight", En, "Night (00:00–06:00)"),
        new("TimeFilterMorning", En, "Morning (06:00–12:00)"),
        new("TimeFilterAfternoon", En, "Afternoon (12:00–18:00)"),
        new("TimeFilterEvening", En, "Evening (18:00–24:00)"),
        new("BusTypeFilterLabel", En, "Seat layout"),
        new("FiltersNoMatchBody", En, "No journeys match the selected filters."),
        new("FiltersAllLabel", En, "All"),
        new("FiltersActiveLabel", En, "{0} selected"),
        new("CloseFiltersLabel", En, "Close"),
    ];

    /// <summary>
    /// 2026-09-30'da canlı API'den (İstanbul Avrupa → Ankara) dönen özellikler. Türkçe adlar API'nin döndürdüğü
    /// metnin birebir aynısıdır (yazım hataları dahil); yeni görülen özellikler çalışma zamanında Türkçe olarak eklenir.
    /// </summary>
    public static IReadOnlyList<FeatureTranslation> FeatureTranslations { get; } =
    [
        new(4, Tr, "Molalı"),
        new(7, Tr, "220 Voltluk Priz"),
        new(8, Tr, "USB ile Şarj İmkanı"),
        new(9, Tr, "Okuma lambası"),
        new(10, Tr, "Kablosuz Internet (WiFi)"),
        new(11, Tr, "Ortak TV yayını"),
        new(12, Tr, "Ortak müzik yayını"),
        new(13, Tr, "10 Inc (Büyük) Koltuk Ekranı"),
        new(14, Tr, "Koltuk ekraninda TV yayını"),
        new(15, Tr, "Koltuk ekraninda müzik yayını"),
        new(16, Tr, "Koltuk ekranında radyo"),
        new(20, Tr, "Kulaklık Dağıtımı"),
        new(21, Tr, "Cep telefonu kullanımı serbest"),
        new(22, Tr, "Namaz vakitlerinde duruyor"),
        new(25, Tr, "Rahat Koltuk"),
        new(30, Tr, "Ek Sefer"),
        new(31, Tr, "Jumbo Sefer"),
        new(32, Tr, "Yeni Otoban"),
        new(45, Tr, "Niğde Otobanı"),
        new(72, Tr, "QR Kod ile Multimedya Erişimi"),
        new(87, Tr, "150₺ İndirim Kodu"),
        new(120, Tr, "120₺ İndirim Kodu"),
        new(135, Tr, "70₺ İndirim Kodu"),
        new(178, Tr, "200₺ İndirim Kodu"),
        new(184, Tr, "beIN CONNECT yayını bulunmaktadır"),
        new(192, Tr, "100₺ İndirim Kodu"),
        new(194, Tr, "Relax Sefer"),
        new(211, Tr, "USB Type-C"),
        new(222, Tr, "150₺ İndirim Kodu"),
        new(223, Tr, "100₺ İndirim Kodu"),

        new(4, En, "Rest stops"),
        new(7, En, "220V power outlet"),
        new(8, En, "USB charging"),
        new(9, En, "Reading light"),
        new(10, En, "Wireless internet (WiFi)"),
        new(11, En, "Shared TV broadcast"),
        new(12, En, "Shared music broadcast"),
        new(13, En, "10-inch (large) seat screen"),
        new(14, En, "TV on seat screen"),
        new(15, En, "Music on seat screen"),
        new(16, En, "Radio on seat screen"),
        new(20, En, "Headphones provided"),
        new(21, En, "Mobile phone use allowed"),
        new(22, En, "Stops at prayer times"),
        new(25, En, "Comfortable seat"),
        new(30, En, "Extra journey"),
        new(31, En, "Jumbo journey"),
        new(32, En, "New highway"),
        new(45, En, "Niğde highway"),
        new(72, En, "Multimedia access via QR code"),
        new(87, En, "₺150 discount code"),
        new(120, En, "₺120 discount code"),
        new(135, En, "₺70 discount code"),
        new(178, En, "₺200 discount code"),
        new(184, En, "beIN CONNECT streaming available"),
        new(192, En, "₺100 discount code"),
        new(194, En, "Relax journey"),
        new(211, En, "USB Type-C"),
        new(222, En, "₺150 discount code"),
        new(223, En, "₺100 discount code"),
    ];
}
