// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using oBiletCase.Infrastructure.Persistence;

#nullable disable

namespace oBiletCase.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260930090030_InitialLocalization")]
    partial class InitialLocalization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("oBiletCase.Infrastructure.Localization.FeatureTranslation", b =>
                {
                    b.Property<int>("FeatureId")
                        .HasColumnType("integer");

                    b.Property<string>("Culture")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("FeatureId", "Culture");

                    b.ToTable("FeatureTranslations");

                    b.HasData(
                        new
                        {
                            FeatureId = 4,
                            Culture = "tr",
                            Name = "Molalı"
                        },
                        new
                        {
                            FeatureId = 7,
                            Culture = "tr",
                            Name = "220 Voltluk Priz"
                        },
                        new
                        {
                            FeatureId = 8,
                            Culture = "tr",
                            Name = "USB ile Şarj İmkanı"
                        },
                        new
                        {
                            FeatureId = 9,
                            Culture = "tr",
                            Name = "Okuma lambası"
                        },
                        new
                        {
                            FeatureId = 10,
                            Culture = "tr",
                            Name = "Kablosuz Internet (WiFi)"
                        },
                        new
                        {
                            FeatureId = 11,
                            Culture = "tr",
                            Name = "Ortak TV yayını"
                        },
                        new
                        {
                            FeatureId = 12,
                            Culture = "tr",
                            Name = "Ortak müzik yayını"
                        },
                        new
                        {
                            FeatureId = 13,
                            Culture = "tr",
                            Name = "10 Inc (Büyük) Koltuk Ekranı"
                        },
                        new
                        {
                            FeatureId = 14,
                            Culture = "tr",
                            Name = "Koltuk ekraninda TV yayını"
                        },
                        new
                        {
                            FeatureId = 15,
                            Culture = "tr",
                            Name = "Koltuk ekraninda müzik yayını"
                        },
                        new
                        {
                            FeatureId = 16,
                            Culture = "tr",
                            Name = "Koltuk ekranında radyo"
                        },
                        new
                        {
                            FeatureId = 20,
                            Culture = "tr",
                            Name = "Kulaklık Dağıtımı"
                        },
                        new
                        {
                            FeatureId = 21,
                            Culture = "tr",
                            Name = "Cep telefonu kullanımı serbest"
                        },
                        new
                        {
                            FeatureId = 22,
                            Culture = "tr",
                            Name = "Namaz vakitlerinde duruyor"
                        },
                        new
                        {
                            FeatureId = 25,
                            Culture = "tr",
                            Name = "Rahat Koltuk"
                        },
                        new
                        {
                            FeatureId = 30,
                            Culture = "tr",
                            Name = "Ek Sefer"
                        },
                        new
                        {
                            FeatureId = 31,
                            Culture = "tr",
                            Name = "Jumbo Sefer"
                        },
                        new
                        {
                            FeatureId = 32,
                            Culture = "tr",
                            Name = "Yeni Otoban"
                        },
                        new
                        {
                            FeatureId = 45,
                            Culture = "tr",
                            Name = "Niğde Otobanı"
                        },
                        new
                        {
                            FeatureId = 72,
                            Culture = "tr",
                            Name = "QR Kod ile Multimedya Erişimi"
                        },
                        new
                        {
                            FeatureId = 87,
                            Culture = "tr",
                            Name = "150₺ İndirim Kodu"
                        },
                        new
                        {
                            FeatureId = 120,
                            Culture = "tr",
                            Name = "120₺ İndirim Kodu"
                        },
                        new
                        {
                            FeatureId = 135,
                            Culture = "tr",
                            Name = "70₺ İndirim Kodu"
                        },
                        new
                        {
                            FeatureId = 178,
                            Culture = "tr",
                            Name = "200₺ İndirim Kodu"
                        },
                        new
                        {
                            FeatureId = 184,
                            Culture = "tr",
                            Name = "beIN CONNECT yayını bulunmaktadır"
                        },
                        new
                        {
                            FeatureId = 192,
                            Culture = "tr",
                            Name = "100₺ İndirim Kodu"
                        },
                        new
                        {
                            FeatureId = 194,
                            Culture = "tr",
                            Name = "Relax Sefer"
                        },
                        new
                        {
                            FeatureId = 211,
                            Culture = "tr",
                            Name = "USB Type-C"
                        },
                        new
                        {
                            FeatureId = 222,
                            Culture = "tr",
                            Name = "150₺ İndirim Kodu"
                        },
                        new
                        {
                            FeatureId = 223,
                            Culture = "tr",
                            Name = "100₺ İndirim Kodu"
                        },
                        new
                        {
                            FeatureId = 4,
                            Culture = "en",
                            Name = "Rest stops"
                        },
                        new
                        {
                            FeatureId = 7,
                            Culture = "en",
                            Name = "220V power outlet"
                        },
                        new
                        {
                            FeatureId = 8,
                            Culture = "en",
                            Name = "USB charging"
                        },
                        new
                        {
                            FeatureId = 9,
                            Culture = "en",
                            Name = "Reading light"
                        },
                        new
                        {
                            FeatureId = 10,
                            Culture = "en",
                            Name = "Wireless internet (WiFi)"
                        },
                        new
                        {
                            FeatureId = 11,
                            Culture = "en",
                            Name = "Shared TV broadcast"
                        },
                        new
                        {
                            FeatureId = 12,
                            Culture = "en",
                            Name = "Shared music broadcast"
                        },
                        new
                        {
                            FeatureId = 13,
                            Culture = "en",
                            Name = "10-inch (large) seat screen"
                        },
                        new
                        {
                            FeatureId = 14,
                            Culture = "en",
                            Name = "TV on seat screen"
                        },
                        new
                        {
                            FeatureId = 15,
                            Culture = "en",
                            Name = "Music on seat screen"
                        },
                        new
                        {
                            FeatureId = 16,
                            Culture = "en",
                            Name = "Radio on seat screen"
                        },
                        new
                        {
                            FeatureId = 20,
                            Culture = "en",
                            Name = "Headphones provided"
                        },
                        new
                        {
                            FeatureId = 21,
                            Culture = "en",
                            Name = "Mobile phone use allowed"
                        },
                        new
                        {
                            FeatureId = 22,
                            Culture = "en",
                            Name = "Stops at prayer times"
                        },
                        new
                        {
                            FeatureId = 25,
                            Culture = "en",
                            Name = "Comfortable seat"
                        },
                        new
                        {
                            FeatureId = 30,
                            Culture = "en",
                            Name = "Extra journey"
                        },
                        new
                        {
                            FeatureId = 31,
                            Culture = "en",
                            Name = "Jumbo journey"
                        },
                        new
                        {
                            FeatureId = 32,
                            Culture = "en",
                            Name = "New highway"
                        },
                        new
                        {
                            FeatureId = 45,
                            Culture = "en",
                            Name = "Niğde highway"
                        },
                        new
                        {
                            FeatureId = 72,
                            Culture = "en",
                            Name = "Multimedia access via QR code"
                        },
                        new
                        {
                            FeatureId = 87,
                            Culture = "en",
                            Name = "₺150 discount code"
                        },
                        new
                        {
                            FeatureId = 120,
                            Culture = "en",
                            Name = "₺120 discount code"
                        },
                        new
                        {
                            FeatureId = 135,
                            Culture = "en",
                            Name = "₺70 discount code"
                        },
                        new
                        {
                            FeatureId = 178,
                            Culture = "en",
                            Name = "₺200 discount code"
                        },
                        new
                        {
                            FeatureId = 184,
                            Culture = "en",
                            Name = "beIN CONNECT streaming available"
                        },
                        new
                        {
                            FeatureId = 192,
                            Culture = "en",
                            Name = "₺100 discount code"
                        },
                        new
                        {
                            FeatureId = 194,
                            Culture = "en",
                            Name = "Relax journey"
                        },
                        new
                        {
                            FeatureId = 211,
                            Culture = "en",
                            Name = "USB Type-C"
                        },
                        new
                        {
                            FeatureId = 222,
                            Culture = "en",
                            Name = "₺150 discount code"
                        },
                        new
                        {
                            FeatureId = 223,
                            Culture = "en",
                            Name = "₺100 discount code"
                        });
                });

            modelBuilder.Entity("oBiletCase.Infrastructure.Localization.LocalizationResource", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Culture")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key", "Culture");

                    b.ToTable("LocalizationResources");

                    b.HasData(
                        new
                        {
                            Key = "AppName",
                            Culture = "tr",
                            Value = "oBiletCase"
                        },
                        new
                        {
                            Key = "NavHome",
                            Culture = "tr",
                            Value = "Ana Sayfa"
                        },
                        new
                        {
                            Key = "SkipToContent",
                            Culture = "tr",
                            Value = "İçeriğe geç"
                        },
                        new
                        {
                            Key = "SearchEyebrow",
                            Culture = "tr",
                            Value = "Otobüs biletleri"
                        },
                        new
                        {
                            Key = "SearchTitle",
                            Culture = "tr",
                            Value = "Otobüs bileti ara"
                        },
                        new
                        {
                            Key = "SearchAccent",
                            Culture = "tr",
                            Value = "kalkıştan varışa."
                        },
                        new
                        {
                            Key = "SearchLede",
                            Culture = "tr",
                            Value = "Kalkış, varış ve tarihi seçin. Sonuçlar bir sonraki adımda listelenir."
                        },
                        new
                        {
                            Key = "FooterTagline",
                            Culture = "tr",
                            Value = "Basit arama, net sonuç."
                        },
                        new
                        {
                            Key = "OriginLabel",
                            Culture = "tr",
                            Value = "Nereden"
                        },
                        new
                        {
                            Key = "DestinationLabel",
                            Culture = "tr",
                            Value = "Nereye"
                        },
                        new
                        {
                            Key = "DepartureDateLabel",
                            Culture = "tr",
                            Value = "Gidiş Tarihi"
                        },
                        new
                        {
                            Key = "SwapLocationsLabel",
                            Culture = "tr",
                            Value = "Kalkış ve varışı değiştir"
                        },
                        new
                        {
                            Key = "TodayLabel",
                            Culture = "tr",
                            Value = "Bugün"
                        },
                        new
                        {
                            Key = "TomorrowLabel",
                            Culture = "tr",
                            Value = "Yarın"
                        },
                        new
                        {
                            Key = "SearchButton",
                            Culture = "tr",
                            Value = "Sefer Ara"
                        },
                        new
                        {
                            Key = "OriginPlaceholder",
                            Culture = "tr",
                            Value = "Kalkış noktası seçin"
                        },
                        new
                        {
                            Key = "DestinationPlaceholder",
                            Culture = "tr",
                            Value = "Varış noktası seçin"
                        },
                        new
                        {
                            Key = "ValidationOriginRequired",
                            Culture = "tr",
                            Value = "Kalkış noktası seçilmelidir."
                        },
                        new
                        {
                            Key = "ValidationDestinationRequired",
                            Culture = "tr",
                            Value = "Varış noktası seçilmelidir."
                        },
                        new
                        {
                            Key = "ValidationSameLocation",
                            Culture = "tr",
                            Value = "Kalkış ve varış noktası aynı olamaz."
                        },
                        new
                        {
                            Key = "ValidationPastDate",
                            Culture = "tr",
                            Value = "Gidiş tarihi bugünden önce olamaz."
                        },
                        new
                        {
                            Key = "ValidationDateRequired",
                            Culture = "tr",
                            Value = "Gidiş tarihi seçilmelidir."
                        },
                        new
                        {
                            Key = "ToastDismissLabel",
                            Culture = "tr",
                            Value = "Bildirimi kapat"
                        },
                        new
                        {
                            Key = "LanguageSwitchLabel",
                            Culture = "tr",
                            Value = "Dil"
                        },
                        new
                        {
                            Key = "NoLocationResults",
                            Culture = "tr",
                            Value = "Sonuç bulunamadı"
                        },
                        new
                        {
                            Key = "SearchLocationLoading",
                            Culture = "tr",
                            Value = "Aranıyor..."
                        },
                        new
                        {
                            Key = "SearchLocationError",
                            Culture = "tr",
                            Value = "Lokasyonlar yüklenemedi"
                        },
                        new
                        {
                            Key = "ClearLocationLabel",
                            Culture = "tr",
                            Value = "Seçimi temizle"
                        },
                        new
                        {
                            Key = "DatePickerLabel",
                            Culture = "tr",
                            Value = "Gidiş tarihi seçin"
                        },
                        new
                        {
                            Key = "DatePickerPreviousMonth",
                            Culture = "tr",
                            Value = "Önceki ay"
                        },
                        new
                        {
                            Key = "DatePickerNextMonth",
                            Culture = "tr",
                            Value = "Sonraki ay"
                        },
                        new
                        {
                            Key = "ErrorKicker",
                            Culture = "tr",
                            Value = "Bir sorun oluştu"
                        },
                        new
                        {
                            Key = "ErrorTitle",
                            Culture = "tr",
                            Value = "İstek işlenemedi"
                        },
                        new
                        {
                            Key = "ErrorBody",
                            Culture = "tr",
                            Value = "Beklenmeyen bir hata oluştu. Ana sayfadan yeniden deneyebilirsiniz."
                        },
                        new
                        {
                            Key = "RequestIdLabel",
                            Culture = "tr",
                            Value = "İstek numarası"
                        },
                        new
                        {
                            Key = "BackToSearch",
                            Culture = "tr",
                            Value = "Aramaya dön"
                        },
                        new
                        {
                            Key = "RecentSearchesTitle",
                            Culture = "tr",
                            Value = "Son aramalarınız"
                        },
                        new
                        {
                            Key = "RemoveRecentSearchLabel",
                            Culture = "tr",
                            Value = "Bu aramayı kaldır"
                        },
                        new
                        {
                            Key = "OriginSummaryLabel",
                            Culture = "tr",
                            Value = "Kalkış"
                        },
                        new
                        {
                            Key = "DestinationSummaryLabel",
                            Culture = "tr",
                            Value = "Varış"
                        },
                        new
                        {
                            Key = "DepartureDateSummaryLabel",
                            Culture = "tr",
                            Value = "Tarih"
                        },
                        new
                        {
                            Key = "InvalidSearchNotice",
                            Culture = "tr",
                            Value = "Aramanız artık geçerli değil. Lütfen kriterleri kontrol edip tekrar deneyin."
                        },
                        new
                        {
                            Key = "JourneysResultsTitle",
                            Culture = "tr",
                            Value = "Sefer sonuçları"
                        },
                        new
                        {
                            Key = "JourneysCountSuffix",
                            Culture = "tr",
                            Value = "sefer bulundu"
                        },
                        new
                        {
                            Key = "NoJourneysFoundTitle",
                            Culture = "tr",
                            Value = "Bu tarihte sefer bulunamadı"
                        },
                        new
                        {
                            Key = "NoJourneysFoundBody",
                            Culture = "tr",
                            Value = "Farklı bir tarih veya güzergah deneyebilirsiniz."
                        },
                        new
                        {
                            Key = "JourneysLoadErrorTitle",
                            Culture = "tr",
                            Value = "Seferler yüklenemedi"
                        },
                        new
                        {
                            Key = "JourneysLoadErrorBody",
                            Culture = "tr",
                            Value = "Obilet servisine şu anda ulaşılamıyor. Lütfen daha sonra tekrar deneyin."
                        },
                        new
                        {
                            Key = "DurationLabel",
                            Culture = "tr",
                            Value = "Süre"
                        },
                        new
                        {
                            Key = "AvailableSeatsSuffix",
                            Culture = "tr",
                            Value = "boş koltuk"
                        },
                        new
                        {
                            Key = "ViewOnObiletButton",
                            Culture = "tr",
                            Value = "Obilet'te incele"
                        },
                        new
                        {
                            Key = "PreviousDayLabel",
                            Culture = "tr",
                            Value = "Önceki gün"
                        },
                        new
                        {
                            Key = "NextDayLabel",
                            Culture = "tr",
                            Value = "Sonraki gün"
                        },
                        new
                        {
                            Key = "DayStripLabel",
                            Culture = "tr",
                            Value = "Gidiş tarihi"
                        },
                        new
                        {
                            Key = "SortLabel",
                            Culture = "tr",
                            Value = "Sırala"
                        },
                        new
                        {
                            Key = "SortDepartureAscending",
                            Culture = "tr",
                            Value = "Kalkış (erken → geç)"
                        },
                        new
                        {
                            Key = "SortDepartureDescending",
                            Culture = "tr",
                            Value = "Kalkış (geç → erken)"
                        },
                        new
                        {
                            Key = "SortPriceAscending",
                            Culture = "tr",
                            Value = "Fiyat (düşük → yüksek)"
                        },
                        new
                        {
                            Key = "SortPriceDescending",
                            Culture = "tr",
                            Value = "Fiyat (yüksek → düşük)"
                        },
                        new
                        {
                            Key = "DetailsLabel",
                            Culture = "tr",
                            Value = "Detaylar"
                        },
                        new
                        {
                            Key = "CancellationPolicyLabel",
                            Culture = "tr",
                            Value = "İptal koşulu"
                        },
                        new
                        {
                            Key = "CancellationPolicyValue",
                            Culture = "tr",
                            Value = "Kalkıştan en az {0} saat önce iptal edilebilir."
                        },
                        new
                        {
                            Key = "GovIdRequiredLabel",
                            Culture = "tr",
                            Value = "Kimlik zorunluluğu"
                        },
                        new
                        {
                            Key = "GovIdRequiredYes",
                            Culture = "tr",
                            Value = "TC kimlik numarası gerekli"
                        },
                        new
                        {
                            Key = "GovIdRequiredNo",
                            Culture = "tr",
                            Value = "Kimlik numarası gerekmez"
                        },
                        new
                        {
                            Key = "SeatingPolicyLabel",
                            Culture = "tr",
                            Value = "Oturma düzeni"
                        },
                        new
                        {
                            Key = "SeatingPolicyMixed",
                            Culture = "tr",
                            Value = "Kadın-erkek karışık oturulabilir"
                        },
                        new
                        {
                            Key = "SeatingPolicySeparate",
                            Culture = "tr",
                            Value = "Kadın-erkek ayrı oturma düzeni"
                        },
                        new
                        {
                            Key = "PartnerRatingLabel",
                            Culture = "tr",
                            Value = "Firma puanı"
                        },
                        new
                        {
                            Key = "OvernightBridgeLabel",
                            Culture = "tr",
                            Value = "{0}'ı {1}'ye bağlayan gece"
                        },
                        new
                        {
                            Key = "FiltersTitle",
                            Culture = "tr",
                            Value = "Filtrele"
                        },
                        new
                        {
                            Key = "ClearFiltersButton",
                            Culture = "tr",
                            Value = "Filtreleri temizle"
                        },
                        new
                        {
                            Key = "TimeFilterLabel",
                            Culture = "tr",
                            Value = "Kalkış saati"
                        },
                        new
                        {
                            Key = "TimeFilterNight",
                            Culture = "tr",
                            Value = "Gece (00:00–06:00)"
                        },
                        new
                        {
                            Key = "TimeFilterMorning",
                            Culture = "tr",
                            Value = "Sabah (06:00–12:00)"
                        },
                        new
                        {
                            Key = "TimeFilterAfternoon",
                            Culture = "tr",
                            Value = "Öğlen (12:00–18:00)"
                        },
                        new
                        {
                            Key = "TimeFilterEvening",
                            Culture = "tr",
                            Value = "Akşam (18:00–24:00)"
                        },
                        new
                        {
                            Key = "BusTypeFilterLabel",
                            Culture = "tr",
                            Value = "Koltuk düzeni"
                        },
                        new
                        {
                            Key = "FiltersNoMatchBody",
                            Culture = "tr",
                            Value = "Seçtiğiniz filtrelere uyan sefer bulunamadı."
                        },
                        new
                        {
                            Key = "FiltersAllLabel",
                            Culture = "tr",
                            Value = "Tümü"
                        },
                        new
                        {
                            Key = "FiltersActiveLabel",
                            Culture = "tr",
                            Value = "{0} seçili"
                        },
                        new
                        {
                            Key = "CloseFiltersLabel",
                            Culture = "tr",
                            Value = "Kapat"
                        },
                        new
                        {
                            Key = "AppName",
                            Culture = "en",
                            Value = "oBiletCase"
                        },
                        new
                        {
                            Key = "NavHome",
                            Culture = "en",
                            Value = "Home"
                        },
                        new
                        {
                            Key = "SkipToContent",
                            Culture = "en",
                            Value = "Skip to content"
                        },
                        new
                        {
                            Key = "SearchEyebrow",
                            Culture = "en",
                            Value = "Bus tickets"
                        },
                        new
                        {
                            Key = "SearchTitle",
                            Culture = "en",
                            Value = "Search bus tickets"
                        },
                        new
                        {
                            Key = "SearchAccent",
                            Culture = "en",
                            Value = "from here to there."
                        },
                        new
                        {
                            Key = "SearchLede",
                            Culture = "en",
                            Value = "Choose origin, destination and date. Results are listed in the next step."
                        },
                        new
                        {
                            Key = "FooterTagline",
                            Culture = "en",
                            Value = "Simple search, clear results."
                        },
                        new
                        {
                            Key = "OriginLabel",
                            Culture = "en",
                            Value = "From"
                        },
                        new
                        {
                            Key = "DestinationLabel",
                            Culture = "en",
                            Value = "To"
                        },
                        new
                        {
                            Key = "DepartureDateLabel",
                            Culture = "en",
                            Value = "Departure Date"
                        },
                        new
                        {
                            Key = "SwapLocationsLabel",
                            Culture = "en",
                            Value = "Swap origin and destination"
                        },
                        new
                        {
                            Key = "TodayLabel",
                            Culture = "en",
                            Value = "Today"
                        },
                        new
                        {
                            Key = "TomorrowLabel",
                            Culture = "en",
                            Value = "Tomorrow"
                        },
                        new
                        {
                            Key = "SearchButton",
                            Culture = "en",
                            Value = "Search Journeys"
                        },
                        new
                        {
                            Key = "OriginPlaceholder",
                            Culture = "en",
                            Value = "Select departure location"
                        },
                        new
                        {
                            Key = "DestinationPlaceholder",
                            Culture = "en",
                            Value = "Select arrival location"
                        },
                        new
                        {
                            Key = "ValidationOriginRequired",
                            Culture = "en",
                            Value = "Departure location is required."
                        },
                        new
                        {
                            Key = "ValidationDestinationRequired",
                            Culture = "en",
                            Value = "Arrival location is required."
                        },
                        new
                        {
                            Key = "ValidationSameLocation",
                            Culture = "en",
                            Value = "Departure and arrival location cannot be the same."
                        },
                        new
                        {
                            Key = "ValidationPastDate",
                            Culture = "en",
                            Value = "Departure date cannot be in the past."
                        },
                        new
                        {
                            Key = "ValidationDateRequired",
                            Culture = "en",
                            Value = "Departure date is required."
                        },
                        new
                        {
                            Key = "ToastDismissLabel",
                            Culture = "en",
                            Value = "Dismiss notification"
                        },
                        new
                        {
                            Key = "LanguageSwitchLabel",
                            Culture = "en",
                            Value = "Language"
                        },
                        new
                        {
                            Key = "NoLocationResults",
                            Culture = "en",
                            Value = "No results found"
                        },
                        new
                        {
                            Key = "SearchLocationLoading",
                            Culture = "en",
                            Value = "Searching..."
                        },
                        new
                        {
                            Key = "SearchLocationError",
                            Culture = "en",
                            Value = "Locations could not be loaded"
                        },
                        new
                        {
                            Key = "ClearLocationLabel",
                            Culture = "en",
                            Value = "Clear selection"
                        },
                        new
                        {
                            Key = "DatePickerLabel",
                            Culture = "en",
                            Value = "Choose departure date"
                        },
                        new
                        {
                            Key = "DatePickerPreviousMonth",
                            Culture = "en",
                            Value = "Previous month"
                        },
                        new
                        {
                            Key = "DatePickerNextMonth",
                            Culture = "en",
                            Value = "Next month"
                        },
                        new
                        {
                            Key = "ErrorKicker",
                            Culture = "en",
                            Value = "Something went wrong"
                        },
                        new
                        {
                            Key = "ErrorTitle",
                            Culture = "en",
                            Value = "The request could not be processed"
                        },
                        new
                        {
                            Key = "ErrorBody",
                            Culture = "en",
                            Value = "An unexpected error occurred. You can try again from the home page."
                        },
                        new
                        {
                            Key = "RequestIdLabel",
                            Culture = "en",
                            Value = "Request ID"
                        },
                        new
                        {
                            Key = "BackToSearch",
                            Culture = "en",
                            Value = "Back to search"
                        },
                        new
                        {
                            Key = "RecentSearchesTitle",
                            Culture = "en",
                            Value = "Your recent searches"
                        },
                        new
                        {
                            Key = "RemoveRecentSearchLabel",
                            Culture = "en",
                            Value = "Remove this search"
                        },
                        new
                        {
                            Key = "OriginSummaryLabel",
                            Culture = "en",
                            Value = "From"
                        },
                        new
                        {
                            Key = "DestinationSummaryLabel",
                            Culture = "en",
                            Value = "To"
                        },
                        new
                        {
                            Key = "DepartureDateSummaryLabel",
                            Culture = "en",
                            Value = "Date"
                        },
                        new
                        {
                            Key = "InvalidSearchNotice",
                            Culture = "en",
                            Value = "Your search is no longer valid. Please check the criteria and try again."
                        },
                        new
                        {
                            Key = "JourneysResultsTitle",
                            Culture = "en",
                            Value = "Journey results"
                        },
                        new
                        {
                            Key = "JourneysCountSuffix",
                            Culture = "en",
                            Value = "journeys found"
                        },
                        new
                        {
                            Key = "NoJourneysFoundTitle",
                            Culture = "en",
                            Value = "No journeys found for this date"
                        },
                        new
                        {
                            Key = "NoJourneysFoundBody",
                            Culture = "en",
                            Value = "Try a different date or route."
                        },
                        new
                        {
                            Key = "JourneysLoadErrorTitle",
                            Culture = "en",
                            Value = "Journeys could not be loaded"
                        },
                        new
                        {
                            Key = "JourneysLoadErrorBody",
                            Culture = "en",
                            Value = "The Obilet service is currently unreachable. Please try again later."
                        },
                        new
                        {
                            Key = "DurationLabel",
                            Culture = "en",
                            Value = "Duration"
                        },
                        new
                        {
                            Key = "AvailableSeatsSuffix",
                            Culture = "en",
                            Value = "seats available"
                        },
                        new
                        {
                            Key = "ViewOnObiletButton",
                            Culture = "en",
                            Value = "View on Obilet"
                        },
                        new
                        {
                            Key = "PreviousDayLabel",
                            Culture = "en",
                            Value = "Previous day"
                        },
                        new
                        {
                            Key = "NextDayLabel",
                            Culture = "en",
                            Value = "Next day"
                        },
                        new
                        {
                            Key = "DayStripLabel",
                            Culture = "en",
                            Value = "Departure date"
                        },
                        new
                        {
                            Key = "SortLabel",
                            Culture = "en",
                            Value = "Sort by"
                        },
                        new
                        {
                            Key = "SortDepartureAscending",
                            Culture = "en",
                            Value = "Departure (earliest first)"
                        },
                        new
                        {
                            Key = "SortDepartureDescending",
                            Culture = "en",
                            Value = "Departure (latest first)"
                        },
                        new
                        {
                            Key = "SortPriceAscending",
                            Culture = "en",
                            Value = "Price (low to high)"
                        },
                        new
                        {
                            Key = "SortPriceDescending",
                            Culture = "en",
                            Value = "Price (high to low)"
                        },
                        new
                        {
                            Key = "DetailsLabel",
                            Culture = "en",
                            Value = "Details"
                        },
                        new
                        {
                            Key = "CancellationPolicyLabel",
                            Culture = "en",
                            Value = "Cancellation policy"
                        },
                        new
                        {
                            Key = "CancellationPolicyValue",
                            Culture = "en",
                            Value = "Can be cancelled at least {0} hours before departure."
                        },
                        new
                        {
                            Key = "GovIdRequiredLabel",
                            Culture = "en",
                            Value = "ID requirement"
                        },
                        new
                        {
                            Key = "GovIdRequiredYes",
                            Culture = "en",
                            Value = "National ID number required"
                        },
                        new
                        {
                            Key = "GovIdRequiredNo",
                            Culture = "en",
                            Value = "No ID number required"
                        },
                        new
                        {
                            Key = "SeatingPolicyLabel",
                            Culture = "en",
                            Value = "Seating policy"
                        },
                        new
                        {
                            Key = "SeatingPolicyMixed",
                            Culture = "en",
                            Value = "Mixed-gender seating allowed"
                        },
                        new
                        {
                            Key = "SeatingPolicySeparate",
                            Culture = "en",
                            Value = "Separate seating by gender"
                        },
                        new
                        {
                            Key = "PartnerRatingLabel",
                            Culture = "en",
                            Value = "Partner rating"
                        },
                        new
                        {
                            Key = "OvernightBridgeLabel",
                            Culture = "en",
                            Value = "Night linking {0} to {1}"
                        },
                        new
                        {
                            Key = "FiltersTitle",
                            Culture = "en",
                            Value = "Filters"
                        },
                        new
                        {
                            Key = "ClearFiltersButton",
                            Culture = "en",
                            Value = "Clear filters"
                        },
                        new
                        {
                            Key = "TimeFilterLabel",
                            Culture = "en",
                            Value = "Departure time"
                        },
                        new
                        {
                            Key = "TimeFilterNight",
                            Culture = "en",
                            Value = "Night (00:00–06:00)"
                        },
                        new
                        {
                            Key = "TimeFilterMorning",
                            Culture = "en",
                            Value = "Morning (06:00–12:00)"
                        },
                        new
                        {
                            Key = "TimeFilterAfternoon",
                            Culture = "en",
                            Value = "Afternoon (12:00–18:00)"
                        },
                        new
                        {
                            Key = "TimeFilterEvening",
                            Culture = "en",
                            Value = "Evening (18:00–24:00)"
                        },
                        new
                        {
                            Key = "BusTypeFilterLabel",
                            Culture = "en",
                            Value = "Seat layout"
                        },
                        new
                        {
                            Key = "FiltersNoMatchBody",
                            Culture = "en",
                            Value = "No journeys match the selected filters."
                        },
                        new
                        {
                            Key = "FiltersAllLabel",
                            Culture = "en",
                            Value = "All"
                        },
                        new
                        {
                            Key = "FiltersActiveLabel",
                            Culture = "en",
                            Value = "{0} selected"
                        },
                        new
                        {
                            Key = "CloseFiltersLabel",
                            Culture = "en",
                            Value = "Close"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
