using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace oBiletCase.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class InitialLocalization : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "FeatureTranslations",
                columns: table => new
                {
                    FeatureId = table.Column<int>(type: "integer", nullable: false),
                    Culture = table.Column<string>(type: "character varying(8)", maxLength: 8, nullable: false),
                    Name = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FeatureTranslations", x => new { x.FeatureId, x.Culture });
                });

            migrationBuilder.CreateTable(
                name: "LocalizationResources",
                columns: table => new
                {
                    Key = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                    Culture = table.Column<string>(type: "character varying(8)", maxLength: 8, nullable: false),
                    Value = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_LocalizationResources", x => new { x.Key, x.Culture });
                });

            migrationBuilder.InsertData(
                table: "FeatureTranslations",
                columns: new[] { "Culture", "FeatureId", "Name" },
                values: new object[,]
                {
                    { "en", 4, "Rest stops" },
                    { "tr", 4, "Molalı" },
                    { "en", 7, "220V power outlet" },
                    { "tr", 7, "220 Voltluk Priz" },
                    { "en", 8, "USB charging" },
                    { "tr", 8, "USB ile Şarj İmkanı" },
                    { "en", 9, "Reading light" },
                    { "tr", 9, "Okuma lambası" },
                    { "en", 10, "Wireless internet (WiFi)" },
                    { "tr", 10, "Kablosuz Internet (WiFi)" },
                    { "en", 11, "Shared TV broadcast" },
                    { "tr", 11, "Ortak TV yayını" },
                    { "en", 12, "Shared music broadcast" },
                    { "tr", 12, "Ortak müzik yayını" },
                    { "en", 13, "10-inch (large) seat screen" },
                    { "tr", 13, "10 Inc (Büyük) Koltuk Ekranı" },
                    { "en", 14, "TV on seat screen" },
                    { "tr", 14, "Koltuk ekraninda TV yayını" },
                    { "en", 15, "Music on seat screen" },
                    { "tr", 15, "Koltuk ekraninda müzik yayını" },
                    { "en", 16, "Radio on seat screen" },
                    { "tr", 16, "Koltuk ekranında radyo" },
                    { "en", 20, "Headphones provided" },
                    { "tr", 20, "Kulaklık Dağıtımı" },
                    { "en", 21, "Mobile phone use allowed" },
                    { "tr", 21, "Cep telefonu kullanımı serbest" },
                    { "en", 22, "Stops at prayer times" },
                    { "tr", 22, "Namaz vakitlerinde duruyor" },
                    { "en", 25, "Comfortable seat" },
                    { "tr", 25, "Rahat Koltuk" },
                    { "en", 30, "Extra journey" },
                    { "tr", 30, "Ek Sefer" },
                    { "en", 31, "Jumbo journey" },
                    { "tr", 31, "Jumbo Sefer" },
                    { "en", 32, "New highway" },
                    { "tr", 32, "Yeni Otoban" },
                    { "en", 45, "Niğde highway" },
                    { "tr", 45, "Niğde Otobanı" },
                    { "en", 72, "Multimedia access via QR code" },
                    { "tr", 72, "QR Kod ile Multimedya Erişimi" },
                    { "en", 87, "₺150 discount code" },
                    { "tr", 87, "150₺ İndirim Kodu" },
                    { "en", 120, "₺120 discount code" },
                    { "tr", 120, "120₺ İndirim Kodu" },
                    { "en", 135, "₺70 discount code" },
                    { "tr", 135, "70₺ İndirim Kodu" },
                    { "en", 178, "₺200 discount code" },
                    { "tr", 178, "200₺ İndirim Kodu" },
                    { "en", 184, "beIN CONNECT streaming available" },
                    { "tr", 184, "beIN CONNECT yayını bulunmaktadır" },
                    { "en", 192, "₺100 discount code" },
                    { "tr", 192, "100₺ İndirim Kodu" },
                    { "en", 194, "Relax journey" },
                    { "tr", 194, "Relax Sefer" },
                    { "en", 211, "USB Type-C" },
                    { "tr", 211, "USB Type-C" },
                    { "en", 222, "₺150 discount code" },
                    { "tr", 222, "150₺ İndirim Kodu" },
                    { "en", 223, "₺100 discount code" },
                    { "tr", 223, "100₺ İndirim Kodu" }
                });

            migrationBuilder.InsertData(
                table: "LocalizationResources",
                columns: new[] { "Culture", "Key", "Value" },
                values: new object[,]
                {
                    { "en", "AppName", "oBiletCase" },
                    { "tr", "AppName", "oBiletCase" },
                    { "en", "AvailableSeatsSuffix", "seats available" },
                    { "tr", "AvailableSeatsSuffix", "boş koltuk" },
                    { "en", "BackToSearch", "Back to search" },
                    { "tr", "BackToSearch", "Aramaya dön" },
                    { "en", "BusTypeFilterLabel", "Seat layout" },
                    { "tr", "BusTypeFilterLabel", "Koltuk düzeni" },
                    { "en", "CancellationPolicyLabel", "Cancellation policy" },
                    { "tr", "CancellationPolicyLabel", "İptal koşulu" },
                    { "en", "CancellationPolicyValue", "Can be cancelled at least {0} hours before departure." },
                    { "tr", "CancellationPolicyValue", "Kalkıştan en az {0} saat önce iptal edilebilir." },
                    { "en", "ClearFiltersButton", "Clear filters" },
                    { "tr", "ClearFiltersButton", "Filtreleri temizle" },
                    { "en", "ClearLocationLabel", "Clear selection" },
                    { "tr", "ClearLocationLabel", "Seçimi temizle" },
                    { "en", "CloseFiltersLabel", "Close" },
                    { "tr", "CloseFiltersLabel", "Kapat" },
                    { "en", "DatePickerLabel", "Choose departure date" },
                    { "tr", "DatePickerLabel", "Gidiş tarihi seçin" },
                    { "en", "DatePickerNextMonth", "Next month" },
                    { "tr", "DatePickerNextMonth", "Sonraki ay" },
                    { "en", "DatePickerPreviousMonth", "Previous month" },
                    { "tr", "DatePickerPreviousMonth", "Önceki ay" },
                    { "en", "DayStripLabel", "Departure date" },
                    { "tr", "DayStripLabel", "Gidiş tarihi" },
                    { "en", "DepartureDateLabel", "Departure Date" },
                    { "tr", "DepartureDateLabel", "Gidiş Tarihi" },
                    { "en", "DepartureDateSummaryLabel", "Date" },
                    { "tr", "DepartureDateSummaryLabel", "Tarih" },
                    { "en", "DestinationLabel", "To" },
                    { "tr", "DestinationLabel", "Nereye" },
                    { "en", "DestinationPlaceholder", "Select arrival location" },
                    { "tr", "DestinationPlaceholder", "Varış noktası seçin" },
                    { "en", "DestinationSummaryLabel", "To" },
                    { "tr", "DestinationSummaryLabel", "Varış" },
                    { "en", "DetailsLabel", "Details" },
                    { "tr", "DetailsLabel", "Detaylar" },
                    { "en", "DurationLabel", "Duration" },
                    { "tr", "DurationLabel", "Süre" },
                    { "en", "ErrorBody", "An unexpected error occurred. You can try again from the home page." },
                    { "tr", "ErrorBody", "Beklenmeyen bir hata oluştu. Ana sayfadan yeniden deneyebilirsiniz." },
                    { "en", "ErrorKicker", "Something went wrong" },
                    { "tr", "ErrorKicker", "Bir sorun oluştu" },
                    { "en", "ErrorTitle", "The request could not be processed" },
                    { "tr", "ErrorTitle", "İstek işlenemedi" },
                    { "en", "FiltersActiveLabel", "{0} selected" },
                    { "tr", "FiltersActiveLabel", "{0} seçili" },
                    { "en", "FiltersAllLabel", "All" },
                    { "tr", "FiltersAllLabel", "Tümü" },
                    { "en", "FiltersNoMatchBody", "No journeys match the selected filters." },
                    { "tr", "FiltersNoMatchBody", "Seçtiğiniz filtrelere uyan sefer bulunamadı." },
                    { "en", "FiltersTitle", "Filters" },
                    { "tr", "FiltersTitle", "Filtrele" },
                    { "en", "FooterTagline", "Simple search, clear results." },
                    { "tr", "FooterTagline", "Basit arama, net sonuç." },
                    { "en", "GovIdRequiredLabel", "ID requirement" },
                    { "tr", "GovIdRequiredLabel", "Kimlik zorunluluğu" },
                    { "en", "GovIdRequiredNo", "No ID number required" },
                    { "tr", "GovIdRequiredNo", "Kimlik numarası gerekmez" },
                    { "en", "GovIdRequiredYes", "National ID number required" },
                    { "tr", "GovIdRequiredYes", "TC kimlik numarası gerekli" },
                    { "en", "InvalidSearchNotice", "Your search is no longer valid. Please check the criteria and try again." },
                    { "tr", "InvalidSearchNotice", "Aramanız artık geçerli değil. Lütfen kriterleri kontrol edip tekrar deneyin." },
                    { "en", "JourneysCountSuffix", "journeys found" },
                    { "tr", "JourneysCountSuffix", "sefer bulundu" },
                    { "en", "JourneysLoadErrorBody", "The Obilet service is currently unreachable. Please try again later." },
                    { "tr", "JourneysLoadErrorBody", "Obilet servisine şu anda ulaşılamıyor. Lütfen daha sonra tekrar deneyin." },
                    { "en", "JourneysLoadErrorTitle", "Journeys could not be loaded" },
                    { "tr", "JourneysLoadErrorTitle", "Seferler yüklenemedi" },
                    { "en", "JourneysResultsTitle", "Journey results" },
                    { "tr", "JourneysResultsTitle", "Sefer sonuçları" },
                    { "en", "LanguageSwitchLabel", "Language" },
                    { "tr", "LanguageSwitchLabel", "Dil" },
                    { "en", "NavHome", "Home" },
                    { "tr", "NavHome", "Ana Sayfa" },
                    { "en", "NextDayLabel", "Next day" },
                    { "tr", "NextDayLabel", "Sonraki gün" },
                    { "en", "NoJourneysFoundBody", "Try a different date or route." },
                    { "tr", "NoJourneysFoundBody", "Farklı bir tarih veya güzergah deneyebilirsiniz." },
                    { "en", "NoJourneysFoundTitle", "No journeys found for this date" },
                    { "tr", "NoJourneysFoundTitle", "Bu tarihte sefer bulunamadı" },
                    { "en", "NoLocationResults", "No results found" },
                    { "tr", "NoLocationResults", "Sonuç bulunamadı" },
                    { "en", "OriginLabel", "From" },
                    { "tr", "OriginLabel", "Nereden" },
                    { "en", "OriginPlaceholder", "Select departure location" },
                    { "tr", "OriginPlaceholder", "Kalkış noktası seçin" },
                    { "en", "OriginSummaryLabel", "From" },
                    { "tr", "OriginSummaryLabel", "Kalkış" },
                    { "en", "OvernightBridgeLabel", "Night linking {0} to {1}" },
                    { "tr", "OvernightBridgeLabel", "{0}'ı {1}'ye bağlayan gece" },
                    { "en", "PartnerRatingLabel", "Partner rating" },
                    { "tr", "PartnerRatingLabel", "Firma puanı" },
                    { "en", "PreviousDayLabel", "Previous day" },
                    { "tr", "PreviousDayLabel", "Önceki gün" },
                    { "en", "RecentSearchesTitle", "Your recent searches" },
                    { "tr", "RecentSearchesTitle", "Son aramalarınız" },
                    { "en", "RemoveRecentSearchLabel", "Remove this search" },
                    { "tr", "RemoveRecentSearchLabel", "Bu aramayı kaldır" },
                    { "en", "RequestIdLabel", "Request ID" },
                    { "tr", "RequestIdLabel", "İstek numarası" },
                    { "en", "SearchAccent", "from here to there." },
                    { "tr", "SearchAccent", "kalkıştan varışa." },
                    { "en", "SearchButton", "Search Journeys" },
                    { "tr", "SearchButton", "Sefer Ara" },
                    { "en", "SearchEyebrow", "Bus tickets" },
                    { "tr", "SearchEyebrow", "Otobüs biletleri" },
                    { "en", "SearchLede", "Choose origin, destination and date. Results are listed in the next step." },
                    { "tr", "SearchLede", "Kalkış, varış ve tarihi seçin. Sonuçlar bir sonraki adımda listelenir." },
                    { "en", "SearchLocationError", "Locations could not be loaded" },
                    { "tr", "SearchLocationError", "Lokasyonlar yüklenemedi" },
                    { "en", "SearchLocationLoading", "Searching..." },
                    { "tr", "SearchLocationLoading", "Aranıyor..." },
                    { "en", "SearchTitle", "Search bus tickets" },
                    { "tr", "SearchTitle", "Otobüs bileti ara" },
                    { "en", "SeatingPolicyLabel", "Seating policy" },
                    { "tr", "SeatingPolicyLabel", "Oturma düzeni" },
                    { "en", "SeatingPolicyMixed", "Mixed-gender seating allowed" },
                    { "tr", "SeatingPolicyMixed", "Kadın-erkek karışık oturulabilir" },
                    { "en", "SeatingPolicySeparate", "Separate seating by gender" },
                    { "tr", "SeatingPolicySeparate", "Kadın-erkek ayrı oturma düzeni" },
                    { "en", "SkipToContent", "Skip to content" },
                    { "tr", "SkipToContent", "İçeriğe geç" },
                    { "en", "SortDepartureAscending", "Departure (earliest first)" },
                    { "tr", "SortDepartureAscending", "Kalkış (erken → geç)" },
                    { "en", "SortDepartureDescending", "Departure (latest first)" },
                    { "tr", "SortDepartureDescending", "Kalkış (geç → erken)" },
                    { "en", "SortLabel", "Sort by" },
                    { "tr", "SortLabel", "Sırala" },
                    { "en", "SortPriceAscending", "Price (low to high)" },
                    { "tr", "SortPriceAscending", "Fiyat (düşük → yüksek)" },
                    { "en", "SortPriceDescending", "Price (high to low)" },
                    { "tr", "SortPriceDescending", "Fiyat (yüksek → düşük)" },
                    { "en", "SwapLocationsLabel", "Swap origin and destination" },
                    { "tr", "SwapLocationsLabel", "Kalkış ve varışı değiştir" },
                    { "en", "TimeFilterAfternoon", "Afternoon (12:00–18:00)" },
                    { "tr", "TimeFilterAfternoon", "Öğlen (12:00–18:00)" },
                    { "en", "TimeFilterEvening", "Evening (18:00–24:00)" },
                    { "tr", "TimeFilterEvening", "Akşam (18:00–24:00)" },
                    { "en", "TimeFilterLabel", "Departure time" },
                    { "tr", "TimeFilterLabel", "Kalkış saati" },
                    { "en", "TimeFilterMorning", "Morning (06:00–12:00)" },
                    { "tr", "TimeFilterMorning", "Sabah (06:00–12:00)" },
                    { "en", "TimeFilterNight", "Night (00:00–06:00)" },
                    { "tr", "TimeFilterNight", "Gece (00:00–06:00)" },
                    { "en", "ToastDismissLabel", "Dismiss notification" },
                    { "tr", "ToastDismissLabel", "Bildirimi kapat" },
                    { "en", "TodayLabel", "Today" },
                    { "tr", "TodayLabel", "Bugün" },
                    { "en", "TomorrowLabel", "Tomorrow" },
                    { "tr", "TomorrowLabel", "Yarın" },
                    { "en", "ValidationDateRequired", "Departure date is required." },
                    { "tr", "ValidationDateRequired", "Gidiş tarihi seçilmelidir." },
                    { "en", "ValidationDestinationRequired", "Arrival location is required." },
                    { "tr", "ValidationDestinationRequired", "Varış noktası seçilmelidir." },
                    { "en", "ValidationOriginRequired", "Departure location is required." },
                    { "tr", "ValidationOriginRequired", "Kalkış noktası seçilmelidir." },
                    { "en", "ValidationPastDate", "Departure date cannot be in the past." },
                    { "tr", "ValidationPastDate", "Gidiş tarihi bugünden önce olamaz." },
                    { "en", "ValidationSameLocation", "Departure and arrival location cannot be the same." },
                    { "tr", "ValidationSameLocation", "Kalkış ve varış noktası aynı olamaz." },
                    { "en", "ViewOnObiletButton", "View on Obilet" },
                    { "tr", "ViewOnObiletButton", "Obilet'te incele" }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "FeatureTranslations");

            migrationBuilder.DropTable(
                name: "LocalizationResources");
        }
    }
}
